package learningandroid.booobdai.com.constructiondiary.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import learningandroid.booobdai.com.constructiondiary.entity.DiaryBean;

import learningandroid.booobdai.com.constructiondiary.dao.DiaryBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig diaryBeanDaoConfig;

    private final DiaryBeanDao diaryBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        diaryBeanDaoConfig = daoConfigMap.get(DiaryBeanDao.class).clone();
        diaryBeanDaoConfig.initIdentityScope(type);

        diaryBeanDao = new DiaryBeanDao(diaryBeanDaoConfig, this);

        registerDao(DiaryBean.class, diaryBeanDao);
    }
    
    public void clear() {
        diaryBeanDaoConfig.clearIdentityScope();
    }

    public DiaryBeanDao getDiaryBeanDao() {
        return diaryBeanDao;
    }

}
